name: gamequest
version: 1.0.0+1
description: GameQuest - UIC E-Waste Recycling Gamified App

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10
  intl: ^0.20.2
  animated_text_kit: ^4.2.2
  badges: ^3.1.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  file_picker: ^8.0.0
  mime: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env
    - assets/.env
